# Generated by Django 6.0.3 on 2026-03-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='body_fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Body Fat %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='muscle_mass_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Muscle Mass in kg', max_digits=5, null=True),
        ),
    ]
