# Generated by Django 5.1.3 on 2026-03-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_alter_dietplan_id_alter_feetracking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinedietmeal',
            name='time_slot',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlineworkoutsession',
            name='time_slot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
