# Generated by Django 5.1.3 on 2026-03-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_time_slot_to_timefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineworkoutsession',
            name='video',
        ),
        migrations.AddField(
            model_name='onlineworkoutsession',
            name='video_url',
            field=models.URLField(blank=True, help_text='Provide a YouTube embedded link (e.g. https://www.youtube.com/embed/...)', max_length=500, null=True),
        ),
    ]
